// Mocks generated by Mockito 5.3.2 from annotations
// in ceiba_assessment_test/test/features/list_users/data/repositories/list_users_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ceiba_assessment_test/features/list_users/data/datasources/users_local_data_source.dart'
    as _i2;
import 'package:ceiba_assessment_test/features/list_users/data/datasources/users_remote_data_source.dart'
    as _i5;
import 'package:ceiba_assessment_test/features/list_users/data/models/user_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IUsersLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUsersLocalDataSource extends _i1.Mock
    implements _i2.IUsersLocalDataSource {
  @override
  _i3.Future<List<_i4.UserModel>> getUsersList() => (super.noSuchMethod(
        Invocation.method(
          #getUsersList,
          [],
        ),
        returnValue: _i3.Future<List<_i4.UserModel>>.value(<_i4.UserModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.UserModel>>.value(<_i4.UserModel>[]),
      ) as _i3.Future<List<_i4.UserModel>>);
  @override
  _i3.Future<void> saveUsers(List<_i4.UserModel>? users) => (super.noSuchMethod(
        Invocation.method(
          #saveUsers,
          [users],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [IUsersRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUsersRemoteDataSource extends _i1.Mock
    implements _i5.IUsersRemoteDataSource {
  @override
  _i3.Future<List<_i4.UserModel>> getUsersList() => (super.noSuchMethod(
        Invocation.method(
          #getUsersList,
          [],
        ),
        returnValue: _i3.Future<List<_i4.UserModel>>.value(<_i4.UserModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.UserModel>>.value(<_i4.UserModel>[]),
      ) as _i3.Future<List<_i4.UserModel>>);
}
